file(
  STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/mws/include/mws/version.h" MWS_VERSION_PARTS
  REGEX "#define MWS_VERSION_[A-Z]+[ ]+")

string(
  REGEX REPLACE ".+MWS_VERSION_MAJOR[ ]+([0-9]+).*"
  "\\1" MWS_VERSION_MAJOR
  "${MWS_VERSION_PARTS}")
string(REGEX REPLACE ".+MWS_VERSION_MINOR[ ]+([0-9]+).*"
  "\\1" MWS_VERSION_MINOR
  "${MWS_VERSION_PARTS}")
string(REGEX REPLACE ".+MWS_VERSION_PATCH[ ]+([0-9]+).*"
  "\\1" MWS_VERSION_PATCH
  "${MWS_VERSION_PARTS}")

set(MWS_VERSION "${MWS_VERSION_MAJOR}.${MWS_VERSION_MINOR}.${MWS_VERSION_PATCH}")
